<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\KaraokeVideoCreator.Domain\KaraokeVideoCreator.Domain.csproj" />
    <ProjectReference Include="..\KaraokeVideoCreator.Application\KaraokeVideoCreator.Application.csproj" />
    <ProjectReference Include="..\KaraokeVideoCreator.Infrastructure\KaraokeVideoCreator.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
